PRAGMA foreign_keys = ON;
CREATE TABLE brands (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL);
CREATE TABLE product_lines (id TEXT PRIMARY KEY, brand_id TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE, name TEXT NOT NULL, short_description TEXT NOT NULL, description TEXT NOT NULL, hair_types TEXT NOT NULL, purposes TEXT NOT NULL, benefits TEXT NOT NULL, keywords TEXT NOT NULL);
CREATE TABLE products (id TEXT PRIMARY KEY, brand_id TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE, line_id TEXT NOT NULL REFERENCES product_lines(id) ON DELETE CASCADE, name TEXT NOT NULL, category TEXT NOT NULL, description TEXT NOT NULL, purpose TEXT NOT NULL, image TEXT, usage TEXT);
CREATE TABLE hair_types (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE product_hair_types (product_id TEXT REFERENCES products(id) ON DELETE CASCADE, hair_type_id TEXT REFERENCES hair_types(id), PRIMARY KEY(product_id,hair_type_id));
CREATE TABLE product_benefits (product_id TEXT REFERENCES products(id) ON DELETE CASCADE, benefit TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY(product_id,benefit));
CREATE TABLE product_ingredients (product_id TEXT REFERENCES products(id) ON DELETE CASCADE, ingredient TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY(product_id,ingredient));
CREATE TABLE user_progress (user_id TEXT NOT NULL DEFAULT 'local', entity_type TEXT NOT NULL CHECK(entity_type IN ('brand','line','product')), entity_id TEXT NOT NULL, correct_answers INTEGER NOT NULL DEFAULT 0, incorrect_answers INTEGER NOT NULL DEFAULT 0, mastery_score INTEGER NOT NULL DEFAULT 0 CHECK(mastery_score BETWEEN 0 AND 100), last_reviewed_at TEXT NOT NULL, next_review_at TEXT NOT NULL, PRIMARY KEY(user_id,entity_type,entity_id));
CREATE TABLE quiz_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, questions TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE quiz_history (id TEXT PRIMARY KEY, user_id TEXT NOT NULL DEFAULT 'local', session_id TEXT NOT NULL REFERENCES quiz_sessions(id), question_id TEXT NOT NULL, product_id TEXT REFERENCES products(id) ON DELETE SET NULL, line_id TEXT REFERENCES product_lines(id) ON DELETE SET NULL, selected_answer TEXT NOT NULL, correct_answer TEXT NOT NULL, correct INTEGER NOT NULL CHECK(correct IN (0,1)), xp INTEGER NOT NULL, created_at TEXT NOT NULL, UNIQUE(session_id,question_id));
CREATE INDEX idx_lines_brand ON product_lines(brand_id);
CREATE INDEX idx_products_line ON products(line_id);
CREATE INDEX idx_products_brand ON products(brand_id);
CREATE INDEX idx_progress_due ON user_progress(user_id,next_review_at);
CREATE INDEX idx_history_user_date ON quiz_history(user_id,created_at);
CREATE TRIGGER clean_product_progress AFTER DELETE ON products BEGIN DELETE FROM user_progress WHERE entity_type='product' AND entity_id=OLD.id; END;
CREATE TRIGGER clean_line_progress AFTER DELETE ON product_lines BEGIN DELETE FROM user_progress WHERE entity_type='line' AND entity_id=OLD.id; END;
CREATE TRIGGER clean_brand_progress AFTER DELETE ON brands BEGIN DELETE FROM user_progress WHERE entity_type='brand' AND entity_id=OLD.id; END;
