-- Translate unchanged demo text only. Keep IDs, user edits, quiz history and progress intact.
UPDATE brands SET description='Навчальна добірка засобів для салонного стайлінгу й догляду. Звіряйте характеристики з актуальними матеріалами виробника.' WHERE id='milk-shake' AND description='Sample learning collection for salon styling and care. Verify all details against current manufacturer materials.';
UPDATE brands SET description='Навчальна добірка засобів для щоденного та спеціалізованого догляду. Звіряйте характеристики з актуальними матеріалами виробника.' WHERE id='insight' AND description='Sample learning collection for everyday and targeted haircare. Verify all details against current manufacturer materials.';
UPDATE product_lines SET short_description='Стайлінг, захист і тривала фіксація' WHERE id='lifestyling' AND short_description='Styling, protection and long-lasting hold';
UPDATE product_lines SET description='Лінійка для створення форми й об’єму та захисту волосся під час гарячого укладання.' WHERE id='lifestyling' AND description='A styling collection for shaping, building volume and protecting hair during heat styling.';
UPDATE product_lines SET hair_types='["Усі типи волосся"]' WHERE id='lifestyling' AND hair_types='["All hair types"]';
UPDATE product_lines SET purposes='["Стайлінг і фіксація","Термозахист"]' WHERE id='lifestyling' AND purposes='["Styling and hold","Heat protection"]';
UPDATE product_lines SET benefits='["Гнучке укладання","Тривале збереження форми"]' WHERE id='lifestyling' AND benefits='["Flexible styling","Lasting definition"]';
UPDATE product_lines SET keywords='["Стиль","Захист","Фіксація"]' WHERE id='lifestyling' AND keywords='["Style","Protect","Hold"]';
UPDATE product_lines SET short_description='Чіткість завитків і догляд за кучерявим волоссям' WHERE id='curl-passion' AND short_description='Definition and care for curly hair';
UPDATE product_lines SET description='Лінійка для догляду за кучерями та підкреслення їхньої природної форми.' WHERE id='curl-passion' AND description='A collection focused on caring for curls and enhancing their natural shape.';
UPDATE product_lines SET hair_types='["Кучеряве","Хвилясте"]' WHERE id='curl-passion' AND hair_types='["Curly","Wavy"]';
UPDATE product_lines SET purposes='["Підкреслення завитків"]' WHERE id='curl-passion' AND purposes='["Curl definition"]';
UPDATE product_lines SET benefits='["Чіткі завитки","Слухняність волосся"]' WHERE id='curl-passion' AND benefits='["Defined curls","Manageability"]';
UPDATE product_lines SET keywords='["Кучері","Чіткість","Пружність"]' WHERE id='curl-passion' AND keywords='["Curls","Definition","Bounce"]';
UPDATE product_lines SET short_description='Догляд за фарбованим волоссям' WHERE id='color-care' AND short_description='Care for color-treated hair';
UPDATE product_lines SET description='Лінійка для підтримання доглянутого вигляду й м’якості фарбованого волосся.' WHERE id='color-care' AND description='A care collection for maintaining the appearance and softness of color-treated hair.';
UPDATE product_lines SET hair_types='["Фарбоване"]' WHERE id='color-care' AND hair_types='["Color-treated"]';
UPDATE product_lines SET purposes='["Підтримання кольору"]' WHERE id='color-care' AND purposes='["Color maintenance"]';
UPDATE product_lines SET benefits='["Догляд за кольором","М’якість"]' WHERE id='color-care' AND benefits='["Color care","Softness"]';
UPDATE product_lines SET keywords='["Колір","Догляд","Блиск"]' WHERE id='color-care' AND keywords='["Color","Care","Shine"]';
UPDATE product_lines SET short_description='Делікатне очищення для частого миття' WHERE id='daily-use' AND short_description='Gentle cleansing for frequent everyday washing';
UPDATE product_lines SET description='Лінійка для частого очищення та легкого щоденного кондиціонування.' WHERE id='daily-use' AND description='An everyday haircare collection for frequent cleansing and light conditioning.';
UPDATE product_lines SET hair_types='["Усі типи волосся"]' WHERE id='daily-use' AND hair_types='["All hair types"]';
UPDATE product_lines SET purposes='["Часте миття"]' WHERE id='daily-use' AND purposes='["Frequent washing"]';
UPDATE product_lines SET benefits='["Делікатне очищення","Легкий догляд"]' WHERE id='daily-use' AND benefits='["Gentle cleansing","Lightweight care"]';
UPDATE product_lines SET keywords='["Щодня","Делікатність","Свіжість"]' WHERE id='daily-use' AND keywords='["Daily","Gentle","Fresh"]';
UPDATE product_lines SET short_description='Розгладжувальний догляд за неслухняним волоссям' WHERE id='anti-frizz' AND short_description='Smoothing care for frizzy and unruly hair';
UPDATE product_lines SET description='Лінійка для розгладження, полегшення укладання та зменшення пухнастості волосся.' WHERE id='anti-frizz' AND description='A smoothing collection that helps improve manageability and reduce the appearance of frizz.';
UPDATE product_lines SET hair_types='["Схильне до пухнастості","Неслухняне"]' WHERE id='anti-frizz' AND hair_types='["Frizzy","Unruly"]';
UPDATE product_lines SET purposes='["Контроль пухнастості"]' WHERE id='anti-frizz' AND purposes='["Frizz control"]';
UPDATE product_lines SET benefits='["Гладкіше волосся","Легше розчісування"]' WHERE id='anti-frizz' AND benefits='["Smoother hair","Easier detangling"]';
UPDATE product_lines SET keywords='["Гладкість","Слухняність","Пом’якшення"]' WHERE id='anti-frizz' AND keywords='["Smooth","Tame","Soften"]';
UPDATE product_lines SET short_description='Живильний догляд за сухим волоссям' WHERE id='dry-hair' AND short_description='Nourishing care for dry hair';
UPDATE product_lines SET description='Живильна лінійка для сухого волосся, якому потрібна м’якість.' WHERE id='dry-hair' AND description='A nourishing care collection for hair that feels dry and needs softness.';
UPDATE product_lines SET hair_types='["Сухе"]' WHERE id='dry-hair' AND hair_types='["Dry"]';
UPDATE product_lines SET purposes='["Догляд проти сухості"]' WHERE id='dry-hair' AND purposes='["Dryness care"]';
UPDATE product_lines SET benefits='["Живлення","М’якість"]' WHERE id='dry-hair' AND benefits='["Nourishment","Softness"]';
UPDATE product_lines SET keywords='["Живлення","Зволоження","М’якість"]' WHERE id='dry-hair' AND keywords='["Nourish","Moisture","Soft"]';
UPDATE products SET category='Термозахисний засіб' WHERE id='thermo-protector' AND category='Heat protectant';
UPDATE products SET description='Спрей для захисту волосся під час гарячого укладання.' WHERE id='thermo-protector' AND description='A styling spray intended to protect hair during heat styling.';
UPDATE products SET purpose='Термозахист під час укладання' WHERE id='thermo-protector' AND purpose='Heat protection during styling';
UPDATE products SET usage='Перед гарячим укладанням дотримуйтеся інструкції на актуальному пакованні продукту.' WHERE id='thermo-protector' AND usage='Follow the instructions on the current product packaging before heat styling.';
UPDATE OR IGNORE product_benefits SET benefit='Захист від високих температур' WHERE product_id='thermo-protector' AND benefit='Thermal protection';
UPDATE OR IGNORE product_benefits SET benefit='Легше укладання' WHERE product_id='thermo-protector' AND benefit='Easier styling';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='thermo-protector' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Усі типи волосся','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='thermo-protector' AND hair_type_id='All hair types');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'thermo-protector','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='thermo-protector' AND hair_type_id='All hair types');
DELETE FROM product_hair_types WHERE product_id='thermo-protector' AND hair_type_id='All hair types';
UPDATE products SET category='Лак для волосся' WHERE id='eco-strong-hairspray' AND category='Hairspray';
UPDATE products SET description='Фінішний спрей для закріплення готової зачіски.' WHERE id='eco-strong-hairspray' AND description='A finishing spray for keeping a completed hairstyle in place.';
UPDATE products SET purpose='Сильна фінішна фіксація' WHERE id='eco-strong-hairspray' AND purpose='Strong finishing hold';
UPDATE OR IGNORE product_benefits SET benefit='Тривала фіксація' WHERE product_id='eco-strong-hairspray' AND benefit='Long-lasting hold';
UPDATE OR IGNORE product_benefits SET benefit='Контроль зачіски' WHERE product_id='eco-strong-hairspray' AND benefit='Style control';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='eco-strong-hairspray' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Усі типи волосся','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='eco-strong-hairspray' AND hair_type_id='All hair types');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'eco-strong-hairspray','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='eco-strong-hairspray' AND hair_type_id='All hair types');
DELETE FROM product_hair_types WHERE product_id='eco-strong-hairspray' AND hair_type_id='All hair types';
UPDATE products SET category='Пінка для укладання' WHERE id='shaping-foam' AND category='Styling foam';
UPDATE products SET description='Пінка для надання зачісці форми та контролю укладання.' WHERE id='shaping-foam' AND description='A styling foam for shaping and controlling a hairstyle.';
UPDATE products SET purpose='Формування зачіски й контроль укладання' WHERE id='shaping-foam' AND purpose='Shaping and styling control';
UPDATE OR IGNORE product_benefits SET benefit='Збереження форми' WHERE product_id='shaping-foam' AND benefit='Shape control';
UPDATE OR IGNORE product_benefits SET benefit='Підтримка укладання' WHERE product_id='shaping-foam' AND benefit='Styling support';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='shaping-foam' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Усі типи волосся','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='shaping-foam' AND hair_type_id='All hair types');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'shaping-foam','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='shaping-foam' AND hair_type_id='All hair types');
DELETE FROM product_hair_types WHERE product_id='shaping-foam' AND hair_type_id='All hair types';
UPDATE products SET category='Пінка для укладання' WHERE id='volumizing-foam' AND category='Styling foam';
UPDATE products SET description='Легка пінка для надання волоссю об’єму та візуальної густоти.' WHERE id='volumizing-foam' AND description='A lightweight styling foam for adding body and volume.';
UPDATE products SET purpose='Об’єм та укладання' WHERE id='volumizing-foam' AND purpose='Volume and styling';
UPDATE OR IGNORE product_benefits SET benefit='Додатковий об’єм' WHERE product_id='volumizing-foam' AND benefit='Added volume';
UPDATE OR IGNORE product_benefits SET benefit='Візуально густіше волосся' WHERE product_id='volumizing-foam' AND benefit='Fuller-looking hair';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='volumizing-foam' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Тонке','Тонке' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='volumizing-foam' AND hair_type_id='Fine');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'volumizing-foam','Тонке' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='volumizing-foam' AND hair_type_id='Fine');
DELETE FROM product_hair_types WHERE product_id='volumizing-foam' AND hair_type_id='Fine';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Усі типи волосся','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='volumizing-foam' AND hair_type_id='All hair types');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'volumizing-foam','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='volumizing-foam' AND hair_type_id='All hair types');
DELETE FROM product_hair_types WHERE product_id='volumizing-foam' AND hair_type_id='All hair types';
UPDATE products SET category='Шампунь' WHERE id='curl-shampoo' AND category='Shampoo';
UPDATE products SET description='Очищувальний засіб для кучерявого та хвилястого волосся.' WHERE id='curl-shampoo' AND description='A cleansing product for curly and wavy hair.';
UPDATE products SET purpose='Делікатне очищення кучерів' WHERE id='curl-shampoo' AND purpose='Gentle cleansing for curls';
UPDATE OR IGNORE product_benefits SET benefit='Дбайливе очищення кучерів' WHERE product_id='curl-shampoo' AND benefit='Curl-friendly cleansing';
UPDATE OR IGNORE product_benefits SET benefit='Слухняність волосся' WHERE product_id='curl-shampoo' AND benefit='Manageability';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='curl-shampoo' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Кучеряве','Кучеряве' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='curl-shampoo' AND hair_type_id='Curly');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'curl-shampoo','Кучеряве' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='curl-shampoo' AND hair_type_id='Curly');
DELETE FROM product_hair_types WHERE product_id='curl-shampoo' AND hair_type_id='Curly';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Хвилясте','Хвилясте' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='curl-shampoo' AND hair_type_id='Wavy');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'curl-shampoo','Хвилясте' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='curl-shampoo' AND hair_type_id='Wavy');
DELETE FROM product_hair_types WHERE product_id='curl-shampoo' AND hair_type_id='Wavy';
UPDATE products SET category='Кондиціонер' WHERE id='curl-conditioner' AND category='Conditioner';
UPDATE products SET description='Кондиціонувальний засіб для полегшення розчісування кучерявого волосся.' WHERE id='curl-conditioner' AND description='A conditioning product for detangling curly hair.';
UPDATE products SET purpose='Розплутування та пом’якшення кучерів' WHERE id='curl-conditioner' AND purpose='Detangling and softening curls';
UPDATE OR IGNORE product_benefits SET benefit='Легше розплутування кучерів' WHERE product_id='curl-conditioner' AND benefit='Easier curl detangling';
UPDATE OR IGNORE product_benefits SET benefit='М’які кучері' WHERE product_id='curl-conditioner' AND benefit='Soft curls';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='curl-conditioner' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Кучеряве','Кучеряве' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='curl-conditioner' AND hair_type_id='Curly');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'curl-conditioner','Кучеряве' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='curl-conditioner' AND hair_type_id='Curly');
DELETE FROM product_hair_types WHERE product_id='curl-conditioner' AND hair_type_id='Curly';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Хвилясте','Хвилясте' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='curl-conditioner' AND hair_type_id='Wavy');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'curl-conditioner','Хвилясте' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='curl-conditioner' AND hair_type_id='Wavy');
DELETE FROM product_hair_types WHERE product_id='curl-conditioner' AND hair_type_id='Wavy';
UPDATE products SET category='Шампунь' WHERE id='color-shampoo' AND category='Shampoo';
UPDATE products SET description='Шампунь для регулярного очищення фарбованого волосся.' WHERE id='color-shampoo' AND description='A shampoo for the cleansing routine of color-treated hair.';
UPDATE products SET purpose='Очищення фарбованого волосся' WHERE id='color-shampoo' AND purpose='Cleansing color-treated hair';
UPDATE OR IGNORE product_benefits SET benefit='Дбайливе очищення зі збереженням кольору' WHERE product_id='color-shampoo' AND benefit='Color-conscious cleansing';
UPDATE OR IGNORE product_benefits SET benefit='Блиск' WHERE product_id='color-shampoo' AND benefit='Shine';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='color-shampoo' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Фарбоване','Фарбоване' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='color-shampoo' AND hair_type_id='Color-treated');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'color-shampoo','Фарбоване' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='color-shampoo' AND hair_type_id='Color-treated');
DELETE FROM product_hair_types WHERE product_id='color-shampoo' AND hair_type_id='Color-treated';
UPDATE products SET category='Кондиціонер' WHERE id='color-conditioner' AND category='Conditioner';
UPDATE products SET description='Кондиціонувальний догляд для пом’якшення фарбованого волосся.' WHERE id='color-conditioner' AND description='A conditioning step for softening color-treated hair.';
UPDATE products SET purpose='Кондиціонування фарбованого волосся' WHERE id='color-conditioner' AND purpose='Conditioning color-treated hair';
UPDATE OR IGNORE product_benefits SET benefit='М’якість фарбованого волосся' WHERE product_id='color-conditioner' AND benefit='Color-treated hair softness';
UPDATE OR IGNORE product_benefits SET benefit='Розплутування' WHERE product_id='color-conditioner' AND benefit='Detangling';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='color-conditioner' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Фарбоване','Фарбоване' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='color-conditioner' AND hair_type_id='Color-treated');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'color-conditioner','Фарбоване' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='color-conditioner' AND hair_type_id='Color-treated');
DELETE FROM product_hair_types WHERE product_id='color-conditioner' AND hair_type_id='Color-treated';
UPDATE products SET category='Шампунь' WHERE id='energizing-shampoo' AND category='Shampoo';
UPDATE products SET description='Шампунь для частого миття волосся різних типів.' WHERE id='energizing-shampoo' AND description='An everyday shampoo for frequent washing across hair types.';
UPDATE products SET purpose='Часте щоденне очищення' WHERE id='energizing-shampoo' AND purpose='Frequent everyday cleansing';
UPDATE OR IGNORE product_benefits SET benefit='Щоденна свіжість' WHERE product_id='energizing-shampoo' AND benefit='Everyday freshness';
UPDATE OR IGNORE product_benefits SET benefit='Делікатне миття' WHERE product_id='energizing-shampoo' AND benefit='Gentle washing';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='energizing-shampoo' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Усі типи волосся','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='energizing-shampoo' AND hair_type_id='All hair types');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'energizing-shampoo','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='energizing-shampoo' AND hair_type_id='All hair types');
DELETE FROM product_hair_types WHERE product_id='energizing-shampoo' AND hair_type_id='All hair types';
UPDATE products SET category='Кондиціонер' WHERE id='energizing-conditioner' AND category='Conditioner';
UPDATE products SET description='Легке кондиціонування у щоденному догляді за волоссям.' WHERE id='energizing-conditioner' AND description='A light conditioning step in an everyday care routine.';
UPDATE products SET purpose='Легке щоденне кондиціонування' WHERE id='energizing-conditioner' AND purpose='Light everyday conditioning';
UPDATE OR IGNORE product_benefits SET benefit='М’якість без обтяження' WHERE product_id='energizing-conditioner' AND benefit='Lightweight softness';
UPDATE OR IGNORE product_benefits SET benefit='Щоденне полегшення розчісування' WHERE product_id='energizing-conditioner' AND benefit='Everyday detangling';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='energizing-conditioner' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Усі типи волосся','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='energizing-conditioner' AND hair_type_id='All hair types');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'energizing-conditioner','Усі типи волосся' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='energizing-conditioner' AND hair_type_id='All hair types');
DELETE FROM product_hair_types WHERE product_id='energizing-conditioner' AND hair_type_id='All hair types';
UPDATE products SET category='Шампунь' WHERE id='anti-frizz-shampoo' AND category='Shampoo';
UPDATE products SET description='Очищувальний засіб для неслухняного та схильного до пухнастості волосся.' WHERE id='anti-frizz-shampoo' AND description='A cleansing product for frizzy and unruly hair.';
UPDATE products SET purpose='Очищення волосся, схильного до пухнастості' WHERE id='anti-frizz-shampoo' AND purpose='Cleansing frizzy hair';
UPDATE OR IGNORE product_benefits SET benefit='Очищення з розгладжувальним ефектом' WHERE product_id='anti-frizz-shampoo' AND benefit='Smoothing cleansing';
UPDATE OR IGNORE product_benefits SET benefit='Слухняне волосся' WHERE product_id='anti-frizz-shampoo' AND benefit='Manageable hair';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='anti-frizz-shampoo' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Схильне до пухнастості','Схильне до пухнастості' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='anti-frizz-shampoo' AND hair_type_id='Frizzy');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'anti-frizz-shampoo','Схильне до пухнастості' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='anti-frizz-shampoo' AND hair_type_id='Frizzy');
DELETE FROM product_hair_types WHERE product_id='anti-frizz-shampoo' AND hair_type_id='Frizzy';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Неслухняне','Неслухняне' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='anti-frizz-shampoo' AND hair_type_id='Unruly');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'anti-frizz-shampoo','Неслухняне' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='anti-frizz-shampoo' AND hair_type_id='Unruly');
DELETE FROM product_hair_types WHERE product_id='anti-frizz-shampoo' AND hair_type_id='Unruly';
UPDATE products SET category='Маска' WHERE id='anti-frizz-mask' AND category='Mask';
UPDATE products SET description='Кондиціонувальний догляд для розгладження неслухняного волосся.' WHERE id='anti-frizz-mask' AND description='A conditioning treatment for smoothing unruly hair.';
UPDATE products SET purpose='Інтенсивне розгладження пухнастості' WHERE id='anti-frizz-mask' AND purpose='Intensive frizz smoothing';
UPDATE OR IGNORE product_benefits SET benefit='Зменшення пухнастості' WHERE product_id='anti-frizz-mask' AND benefit='Frizz reduction';
UPDATE OR IGNORE product_benefits SET benefit='Глибоке пом’якшення' WHERE product_id='anti-frizz-mask' AND benefit='Deep softening';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='anti-frizz-mask' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Схильне до пухнастості','Схильне до пухнастості' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='anti-frizz-mask' AND hair_type_id='Frizzy');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'anti-frizz-mask','Схильне до пухнастості' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='anti-frizz-mask' AND hair_type_id='Frizzy');
DELETE FROM product_hair_types WHERE product_id='anti-frizz-mask' AND hair_type_id='Frizzy';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Неслухняне','Неслухняне' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='anti-frizz-mask' AND hair_type_id='Unruly');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'anti-frizz-mask','Неслухняне' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='anti-frizz-mask' AND hair_type_id='Unruly');
DELETE FROM product_hair_types WHERE product_id='anti-frizz-mask' AND hair_type_id='Unruly';
UPDATE products SET category='Шампунь' WHERE id='nourishing-shampoo' AND category='Shampoo';
UPDATE products SET description='Очищувальний засіб для сухого волосся.' WHERE id='nourishing-shampoo' AND description='A cleansing product for hair that feels dry.';
UPDATE products SET purpose='Очищення сухого волосся' WHERE id='nourishing-shampoo' AND purpose='Cleansing dry hair';
UPDATE OR IGNORE product_benefits SET benefit='Очищення з живильним доглядом' WHERE product_id='nourishing-shampoo' AND benefit='Nourishing cleansing';
UPDATE OR IGNORE product_benefits SET benefit='Догляд за сухим волоссям' WHERE product_id='nourishing-shampoo' AND benefit='Dry hair care';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='nourishing-shampoo' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Сухе','Сухе' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='nourishing-shampoo' AND hair_type_id='Dry');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'nourishing-shampoo','Сухе' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='nourishing-shampoo' AND hair_type_id='Dry');
DELETE FROM product_hair_types WHERE product_id='nourishing-shampoo' AND hair_type_id='Dry';
UPDATE products SET category='Маска' WHERE id='nourishing-mask' AND category='Mask';
UPDATE products SET description='Насичений кондиціонувальний догляд за сухим волоссям.' WHERE id='nourishing-mask' AND description='A rich conditioning treatment for dry hair.';
UPDATE products SET purpose='Інтенсивне живлення сухого волосся' WHERE id='nourishing-mask' AND purpose='Intensive nourishment for dry hair';
UPDATE OR IGNORE product_benefits SET benefit='Глибоке живлення' WHERE product_id='nourishing-mask' AND benefit='Deep nourishment';
UPDATE OR IGNORE product_benefits SET benefit='Покращення м’якості' WHERE product_id='nourishing-mask' AND benefit='Improved softness';
UPDATE OR IGNORE product_ingredients SET ingredient='Демонстраційні дані: звірте склад з актуальною етикеткою' WHERE product_id='nourishing-mask' AND ingredient='Sample data: consult current product label';
INSERT OR IGNORE INTO hair_types (id,name) SELECT 'Сухе','Сухе' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='nourishing-mask' AND hair_type_id='Dry');
INSERT OR IGNORE INTO product_hair_types (product_id,hair_type_id) SELECT 'nourishing-mask','Сухе' WHERE EXISTS (SELECT 1 FROM product_hair_types WHERE product_id='nourishing-mask' AND hair_type_id='Dry');
DELETE FROM product_hair_types WHERE product_id='nourishing-mask' AND hair_type_id='Dry';
