-- Separates the learning cue from the full Insight description and enriches verified Anti-frizz copy.
UPDATE products SET purpose='Щоденне очищення сухого й пухнастого волосся з контролем пухнастості',description='Зволожувальний шампунь м’яко очищає сухе, пухнасте й неслухняне волосся, допомагає відновити еластичність, полегшує укладання та залишає волосся гладкішим і блискучим.',usage='Нанесіть невелику кількість шампуню на вологе волосся, спіньте та змийте. За потреби повторіть.' WHERE id='anti-frizz-zvolozhuiuchyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Зволоження та легке розплутування сухого, неслухняного волосся',description='Зволожувальний кондиціонер допомагає сухому волоссю утримувати вологу, пом’якшує його, полегшує розплутування та надає більш гладкого й доглянутого вигляду.',usage='Нанесіть на чисте вологе волосся, рівномірно розподіліть по довжині, залиште на 3–5 хвилин і ретельно змийте.' WHERE id='anti-frizz-zvolozhuiuchyi-kondytsioner' AND brand_id='insight';
UPDATE products SET purpose='Глибоке живлення й розгладження сухого та пухнастого волосся',description='Зволожувальна маска інтенсивно живить сухе, пухнасте й неслухняне волосся, допомагає утримувати вологу, розгладжує волосяне волокно та повертає м’якість, еластичність і блиск.',usage='Нанесіть на вологе волосся та рівномірно розподіліть по всій довжині. Залиште на 5–10 хвилин, потім ретельно змийте.' WHERE id='anti-frizz-zvolozhuiucha-maska-dlia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Очищення волосся, що зазнає впливу міського середовища та оксидативного стресу' WHERE id='antioxidant-antyoksydantnyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Зволоження та розплутування волосся з підтримкою антиоксидантного захисту' WHERE id='antioxidant-antyoksydantnyi-kondytsioner' AND brand_id='insight';
UPDATE products SET purpose='Інтенсивне відновлення щільності й блиску волосся, ослабленого зовнішніми чинниками' WHERE id='antioxidant-antyoksydantna-maska-dlia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Щоденний незмивний захист волосся від сонця, погоди й міського середовища' WHERE id='antioxidant-sprei-dlia-zakhystu-volossia' AND brand_id='insight';
UPDATE products SET purpose='Очищення блонду з нейтралізацією небажаних жовто-оранжевих відтінків' WHERE id='blonde-shampun-dlia-kholodnykh-vidtinkiv-blond-ta-siaiva' AND brand_id='insight';
UPDATE products SET purpose='Живлення освітленого волосся та підтримання чистого холодного відтінку' WHERE id='blonde-maska-dlia-volossia-shcho-pidsyliuie-kholodni-vidtinky-blond' AND brand_id='insight';
UPDATE products SET purpose='Регулярне очищення чутливої шкіри голови, схильної до лупи' WHERE id='clarifying-ochyshchuiuchyi-dohliad' AND brand_id='insight';
UPDATE products SET purpose='Курсовий незмивний догляд для шкіри голови з проявами лупи' WHERE id='clarifying-ochyshchuiuchyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Делікатне очищення фарбованого волосся зі збереженням яскравості кольору' WHERE id='colored-hair-zakhysnyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Розплутування й зволоження фарбованого волосся після миття' WHERE id='colored-hair-zakhysnyi-kondytsioner' AND brand_id='insight';
UPDATE products SET purpose='Інтенсивний кислий догляд для запечатування кутикули та захисту кольору' WHERE id='colored-hair-zakhysna-maska-dlia-volossia' AND brand_id='insight';
UPDATE products SET purpose='М’яке щоденне очищення волосся без пересушування' WHERE id='daily-use-enerhezuiuchyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Швидке освіження коренів і відновлення об’єму між миттями' WHERE id='daily-use-sukhyi-shampun-dlia-ob-iemu' AND brand_id='insight';
UPDATE products SET purpose='Щоденне кондиціонування, зволоження та блиск без обтяження' WHERE id='daily-use-enerhetychnyi-kondytsioner-dlia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Щоденне незмивне зволоження та полегшення розчісування' WHERE id='daily-use-nezmyvnyi-kondytsioner-dlia-rozplutuvannia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Регулярне інтенсивне зволоження волосся без втрати легкості' WHERE id='daily-use-enerhetychna-maska-dlia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Очищення пошкодженого волосся з підтримкою міцності та еластичності' WHERE id='damaged-hair-vidnovliuvalnyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Відновлювальне кондиціонування пошкодженого й ослабленого волосся' WHERE id='damaged-hair-vidnovliuvalnyi-kondytsioner' AND brand_id='insight';
UPDATE products SET purpose='Глибоке зміцнення ламкого волосся та повернення щільності' WHERE id='damaged-hair-vidnovliuvalna-maska-dlia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Незмивне відновлення й розгладження пошкодженого волосся' WHERE id='damaged-hair-vidnovliuvalnyi-sprei-dlia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Очищення ослабленого волосся та тонізування шкіри голови' WHERE id='densifying-zmitsniuiuchyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Курсовий догляд для зміцнення коренів і зменшення випадіння' WHERE id='densifying-zmitsniuiuchyi-dohliad' AND brand_id='insight';
UPDATE products SET purpose='Делікатне очищення дуже сухого, тьмяного та ламкого волосся' WHERE id='dry-hair-pozhyvnyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Живлення й розплутування сухого волосся після миття' WHERE id='dry-hair-pozhyvnyi-kondytsioner' AND brand_id='insight';
UPDATE products SET purpose='Глибоке живлення сухого волосся та відновлення його м’якості' WHERE id='dry-hair-pozhyvna-maska-dlia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Делікатне очищення кучерів зі збереженням зволоження та легкості' WHERE id='elasti-curl-m-iakyi-ochyshchuiuchyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Моделювання чітких, пружних кучерів із захистом від вологості' WHERE id='elasti-curl-krem-dlia-pidkreslennia-kucheriv' AND brand_id='insight';
UPDATE products SET purpose='Фінішне живлення та блиск кучерів без обтяження' WHERE id='elasti-curl-oliia-dlia-pruzhnykh-kucheriv' AND brand_id='insight';
UPDATE products SET purpose='Незмивна підготовка кучерів до розчісування й укладання' WHERE id='elasti-curl-nezmyvne-molochko-dlia-rozplutuvannia-volossia' AND brand_id='insight';
UPDATE products SET purpose='Легка фіксація та освіження форми кучерів між миттями' WHERE id='elasti-curl-lak-dlia-volossia-z-lehkoiu-fiksatsiieiu' AND brand_id='insight';
UPDATE products SET purpose='Фінішний догляд для блиску, живлення та еластичності кучерів' WHERE id='elasti-curl-oliia-syvorotka-dlia-siaiva-volossia' AND brand_id='insight';
UPDATE products SET purpose='Інтенсивне кондиціонування та розплутування кучерявого волосся' WHERE id='elasti-curl-maska-dlia-rozplutuvannia-kocheriavoho-volossia' AND brand_id='insight';
UPDATE products SET purpose='Делікатне очищення подразненої та чутливої шкіри голови' WHERE id='lenitive-dermo-zaspokiilyvyi-shampun' AND brand_id='insight';
UPDATE products SET purpose='Незмивне заспокоєння шкіри голови при почервонінні й дискомфорті' WHERE id='lenitive-krem-dlia-komfortu-shkiry-holovy' AND brand_id='insight';
UPDATE products SET purpose='Регулярне очищення жирної шкіри голови та контроль надлишку себуму' WHERE id='rebalancing-rebalansin-shampun' AND brand_id='insight';
UPDATE products SET purpose='Періодичне відлущення й детоксикація шкіри голови, схильної до жирності' WHERE id='rebalancing-krem-eksfoliant-dlia-shkiry-holovy' AND brand_id='insight';
UPDATE products SET purpose='Часте делікатне миття чутливої шкіри голови' WHERE id='sensitive-shampun-dlia-chutlyvoi-shkiry-holovy' AND brand_id='insight';
UPDATE products SET purpose='М’яке розплутування волосся без подразнення чутливої шкіри голови' WHERE id='sensitive-kondytsioner-dlia-chutlyvoi-shkiry-holovy' AND brand_id='insight';
UPDATE products SET purpose='Зволоження та м’якість волосся без обтяження й дискомфорту' WHERE id='sensitive-maska-dlia-chutlyvoi-shkiry-holovy' AND brand_id='insight';
UPDATE products SET purpose='Очищення тонкого волосся з підтриманням легкості та об’єму' WHERE id='volumizing-volume-up-shampoo' AND brand_id='insight';
UPDATE products SET purpose='Прикореневий об’єм і легка фіксація тонкого волосся' WHERE id='volumizing-volume-up-root-lotion' AND brand_id='insight';
UPDATE products SET purpose='Незмивне зволоження тонкого волосся з ефектом щільності та об’єму' WHERE id='volumizing-volume-up-hydrating-spray' AND brand_id='insight';
