-- Adds the DEPOT hair-care catalog extracted from the supplied presentation.
INSERT INTO brands (id,name,description) VALUES ('depot','DEPOT','Професійний бренд засобів для чоловічого догляду, що поєднує класичні формули із сучасним підходом до очищення, догляду та стайлінгу волосся.') ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description;
INSERT INTO product_lines (id,brand_id,name,short_description,description,hair_types,purposes,benefits,keywords,image) VALUES ('depot-100-hair-cleansings','depot','100 Hair Cleansings','Лінійка засобів для очищення волосся та шкіри голови','Засоби для регулярного очищення волосся та шкіри голови з урахуванням різних станів волосся і потреб шкіри голови.','["Нормальне","Жирне","Сухе","Ламке","Світле","Сиве","Знебарвлене"]','["Щоденне очищення","Контроль лупи та себуму","Зволоження","Нейтралізація небажаних теплих тонів"]','["Делікатно очищає","Допомагає підтримувати баланс шкіри голови","Пом’якшує волосся","Освіжає шкіру голови"]','["Очищення","Шампунь","Шкіра голови"]',NULL) ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,hair_types=excluded.hair_types,purposes=excluded.purposes,benefits=excluded.benefits,keywords=excluded.keywords,image=excluded.image;
INSERT INTO product_lines (id,brand_id,name,short_description,description,hair_types,purposes,benefits,keywords,image) VALUES ('depot-200-hair-treatments','depot','200 Hair Treatments','Лінійка кондиціонувальних засобів для волосся','Змивний і незмивний догляд для зволоження, пом’якшення, захисту та кращого контролю волосся.','["Усі типи волосся"]','["Кондиціонування","Зволоження","Захист волосся"]','["Пом’якшує волосся","Зменшує статичність","Полегшує укладання"]','["Догляд","Кондиціонер","Зволоження"]',NULL) ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,hair_types=excluded.hair_types,purposes=excluded.purposes,benefits=excluded.benefits,keywords=excluded.keywords,image=excluded.image;
INSERT INTO product_lines (id,brand_id,name,short_description,description,hair_types,purposes,benefits,keywords,image) VALUES ('depot-300-hair-stylings','depot','300 Hair Stylings','Лінійка засобів для моделювання та фіксації зачіски','Стайлінгові засоби для створення форми, текстури, об’єму, блиску або матового ефекту з різним рівнем фіксації.','["Тонке"]','["Моделювання зачіски","Фіксація","Текстурування","Надання об’єму"]','["Допомагає контролювати форму","Створює текстуру","Підтримує укладку"]','["Стайлінг","Фіксація","Текстура","Об’єм"]',NULL) ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,hair_types=excluded.hair_types,purposes=excluded.purposes,benefits=excluded.benefits,keywords=excluded.keywords,image=excluded.image;
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-101-normalizing-daily-shampoo','depot','depot-100-hair-cleansings','No. 101 Normalizing Daily Shampoo','Шампунь','Нормалізувальний і тонізувальний шампунь із делікатними ПАР без SLES. Підходить для щоденного очищення нормального волосся.','Щоденне делікатне очищення нормального волосся','/images/depot/depot-101-normalizing-daily-shampoo.webp','Нанести на вологе волосся та легко помасажувати шкіру голови. Залишити на кілька хвилин до відчуття свіжості, ретельно змити; за потреби повторити й продовжити догляд кондиціонувальним засобом.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-101-normalizing-daily-shampoo';
DELETE FROM product_benefits WHERE product_id='depot-101-normalizing-daily-shampoo';
DELETE FROM product_ingredients WHERE product_id='depot-101-normalizing-daily-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Нормальне','Нормальне') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-101-normalizing-daily-shampoo','Нормальне');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-101-normalizing-daily-shampoo','Делікатно очищає','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-101-normalizing-daily-shampoo','Тонізує','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-101-normalizing-daily-shampoo','Освіжає шкіру голови','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-101-normalizing-daily-shampoo','Кондиціонує волосся','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-101-normalizing-daily-shampoo','Делікатні ПАР','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-101-normalizing-daily-shampoo','Ботанічний комплекс із 14 рослинних екстрактів','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-101-normalizing-daily-shampoo','Провітамін B5','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-101-normalizing-daily-shampoo','Ефірна олія шавлії','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-101-normalizing-daily-shampoo','Евкаліптол','4');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','depot','depot-100-hair-cleansings','No. 102 Anti-Dandruff & Sebum Control Shampoo','Шампунь','Шампунь із делікатними ПАР без SLES для жирного волосся та шкіри голови, схильної до лупи. Допомагає зменшувати надлишок себуму й відновлювати баланс шкіри голови та волосся.','Контроль лупи та надлишкового себуму','/images/depot/depot-102-anti-dandruff-sebum-control-shampoo.webp','Нанести на вологе волосся та легко помасажувати шкіру голови. Залишити на кілька хвилин, ретельно змити; за потреби повторити.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-102-anti-dandruff-sebum-control-shampoo';
DELETE FROM product_benefits WHERE product_id='depot-102-anti-dandruff-sebum-control-shampoo';
DELETE FROM product_ingredients WHERE product_id='depot-102-anti-dandruff-sebum-control-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Жирне','Жирне') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Жирне');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Допомагає зменшити лупу','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Прибирає надлишок себуму','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Відновлює баланс шкіри голови','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Освіжає та заспокоює шкіру голови','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','М’які ПАР','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Ботанічний комплекс із 10 рослинних екстрактів','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Силікат магнію та алюмінію','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Піритіон цинку','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Алантоїн','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Ефірна олія розмарину','5');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Ефірна олія шавлії','6');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Евкаліптол','7');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-102-anti-dandruff-sebum-control-shampoo','Ментол','8');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-103-hydrating-shampoo','depot','depot-100-hair-cleansings','No. 103 Hydrating Shampoo','Шампунь','Зволожувальний шампунь із делікатними ПАР без SLES для сухого й ламкого волосся. М’яко очищає, зволожує та пом’якшує волосся.','Делікатне очищення та зволоження сухого й ламкого волосся','/images/depot/depot-103-hydrating-shampoo.webp','Нанести на вологе волосся та легко помасажувати шкіру голови. Залишити на кілька хвилин до відчуття свіжості, ретельно змити; за потреби повторити й продовжити догляд кондиціонувальним засобом.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-103-hydrating-shampoo';
DELETE FROM product_benefits WHERE product_id='depot-103-hydrating-shampoo';
DELETE FROM product_ingredients WHERE product_id='depot-103-hydrating-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Сухе','Сухе') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-103-hydrating-shampoo','Сухе');
INSERT INTO hair_types (id,name) VALUES ('Ламке','Ламке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-103-hydrating-shampoo','Ламке');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-103-hydrating-shampoo','М’яко очищає','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-103-hydrating-shampoo','Зволожує','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-103-hydrating-shampoo','Пом’якшує','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-103-hydrating-shampoo','Зменшує статичність','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-103-hydrating-shampoo','Делікатні ПАР','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-103-hydrating-shampoo','Сік алое','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-103-hydrating-shampoo','Провітамін B5','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-103-hydrating-shampoo','Амінокислоти та протеїни шовку','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-103-hydrating-shampoo','Пшеничні протеїни','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-103-hydrating-shampoo','Екстракт імбиру','5');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-103-hydrating-shampoo','Олія макадамії','6');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-104-silver-shampoo','depot','depot-100-hair-cleansings','No. 104 Silver Shampoo','Шампунь','Шампунь із делікатними ПАР без SLES і синьо-фіолетовими пігментами. Допомагає підсилювати природні відтінки білого та сивого волосся й протидіяти небажаним жовтим або мідним тонам.','Нейтралізація жовтих і мідних тонів у світлому, сивому та знебарвленому волоссі','/images/depot/depot-104-silver-shampoo.webp','Нанести на вологе волосся та легко помасажувати шкіру голови. Залишити на кілька хвилин, ретельно змити; за потреби повторити й продовжити догляд кондиціонувальним засобом.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-104-silver-shampoo';
DELETE FROM product_benefits WHERE product_id='depot-104-silver-shampoo';
DELETE FROM product_ingredients WHERE product_id='depot-104-silver-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Сиве','Сиве') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-104-silver-shampoo','Сиве');
INSERT INTO hair_types (id,name) VALUES ('Світле','Світле') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-104-silver-shampoo','Світле');
INSERT INTO hair_types (id,name) VALUES ('Знебарвлене','Знебарвлене') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-104-silver-shampoo','Знебарвлене');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-104-silver-shampoo','Делікатно очищає','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-104-silver-shampoo','Нейтралізує небажані теплі тони','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-104-silver-shampoo','Підсилює природний відтінок білого й сивого волосся','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-104-silver-shampoo','Освіжає шкіру голови','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-104-silver-shampoo','Делікатні ПАР','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-104-silver-shampoo','Спеціальний фіолетовий пігмент','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-104-silver-shampoo','Ботанічний комплекс із 10 рослинних екстрактів','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-104-silver-shampoo','Ефірна олія шавлії','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-104-silver-shampoo','Евкаліптол','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-104-silver-shampoo','Ментол','5');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-201-refreshing-conditioner','depot','depot-200-hair-treatments','No. 201 Refreshing Conditioner','Кондиціонер','Тонізувальний і зволожувальний кондиціонер, що освіжає шкіру голови та волосся. Пом’якшує й ущільнює волосся та діє як антистатик.','Зволоження, пом’якшення та освіження волосся і шкіри голови','/images/depot/depot-201-refreshing-conditioner.webp','Нанести на підсушене рушником волосся. Масажними рухами розподілити по шкірі голови та волоссю, залишити на кілька хвилин і ретельно змити.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-201-refreshing-conditioner';
DELETE FROM product_benefits WHERE product_id='depot-201-refreshing-conditioner';
DELETE FROM product_ingredients WHERE product_id='depot-201-refreshing-conditioner';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-201-refreshing-conditioner','Усі типи волосся');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-201-refreshing-conditioner','Зволожує','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-201-refreshing-conditioner','Пом’якшує','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-201-refreshing-conditioner','Ущільнює волосся','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-201-refreshing-conditioner','Зменшує статичність','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-201-refreshing-conditioner','Освіжає шкіру голови','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-201-refreshing-conditioner','Рисова олія','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-201-refreshing-conditioner','Евкаліптол','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-201-refreshing-conditioner','Провітамін B5','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-201-refreshing-conditioner','Ботанічний комплекс із 13 рослинних екстрактів','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-201-refreshing-conditioner','Ефірна олія розмарину','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-201-refreshing-conditioner','Ефірна олія лимона','5');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-202-complete-leave-in-conditioner','depot','depot-200-hair-treatments','No. 202 Complete Leave-in Conditioner','Незмивний кондиціонер','Багатофункціональний незмивний кондиціонер для волосся, який зволожує, кондиціонує, захищає та полегшує контроль під час укладання.','Незмивне кондиціонування та захист волосся','/images/depot/depot-202-complete-leave-in-conditioner.webp','Взяти на руки кількість засобу відповідно до довжини й густоти волосся. Рівномірно нанести на чисте, підсушене рушником волосся, не змивати та продовжити укладання.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-202-complete-leave-in-conditioner';
DELETE FROM product_benefits WHERE product_id='depot-202-complete-leave-in-conditioner';
DELETE FROM product_ingredients WHERE product_id='depot-202-complete-leave-in-conditioner';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-202-complete-leave-in-conditioner','Усі типи волосся');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-202-complete-leave-in-conditioner','Зволожує','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-202-complete-leave-in-conditioner','Кондиціонує','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-202-complete-leave-in-conditioner','Захищає від УФ-випромінювання та зневоднення','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-202-complete-leave-in-conditioner','Полегшує укладання','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-202-complete-leave-in-conditioner','Надає блиску','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-202-complete-leave-in-conditioner','Ботанічний комплекс із 10 рослинних екстрактів','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-202-complete-leave-in-conditioner','Кондиціонувальні речовини','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-202-complete-leave-in-conditioner','Силіконові емоленти','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-202-complete-leave-in-conditioner','УФ-фільтри','3');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-301-matt-paste','depot','depot-300-hair-stylings','No. 301 Matt Paste','Паста для стайлінгу','Паста-помада сильної фіксації для контролю волосся та створення чіткої форми. Забезпечує тривалу укладку з матовим ефектом.','Сильна фіксація та чітка форма з матовим ефектом','/images/depot/depot-301-matt-paste.webp','Взяти невелику кількість засобу, розігріти в руках і нанести на волосся для бажаної укладки.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-301-matt-paste';
DELETE FROM product_benefits WHERE product_id='depot-301-matt-paste';
DELETE FROM product_ingredients WHERE product_id='depot-301-matt-paste';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-301-matt-paste','Усі типи волосся');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-301-matt-paste','Забезпечує сильну фіксацію','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-301-matt-paste','Створює матовий ефект','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-301-matt-paste','Допомагає формувати чіткі контури','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-301-matt-paste','Підтримує укладку протягом тривалого часу','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-301-matt-paste','Воски природного походження','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-301-matt-paste','Ботанічний комплекс із 11 рослинних екстрактів','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-301-matt-paste','Екстракт листя чорного чаю','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-301-matt-paste','Соняшникова олія','3');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-302-clay-pomade','depot','depot-300-hair-stylings','No. 302 Clay Pomade','Глиняна помада','Моделювальна помада з натуральною глиною для створення форми, розділення пасом і напівматового ефекту. Допомагає надавати тонкому волоссю текстуру й об’єм.','Моделювання текстурної укладки з напівматовим ефектом','/images/depot/depot-302-clay-pomade.webp','Взяти потрібну кількість засобу, розігріти в руках і масажними рухами нанести на сухе волосся для укладання.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-302-clay-pomade';
DELETE FROM product_benefits WHERE product_id='depot-302-clay-pomade';
DELETE FROM product_ingredients WHERE product_id='depot-302-clay-pomade';
INSERT INTO hair_types (id,name) VALUES ('Тонке','Тонке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-302-clay-pomade','Тонке');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-302-clay-pomade','Створює текстуру','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-302-clay-pomade','Надає об’єму тонкому волоссю','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-302-clay-pomade','Розділяє пасма','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-302-clay-pomade','Створює напівматовий ефект','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-302-clay-pomade','Захищає від УФ-випромінювання та зневоднення','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-302-clay-pomade','Каолін','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-302-clay-pomade','Гліцерин','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-302-clay-pomade','Ботанічний комплекс із 11 рослинних екстрактів','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-302-clay-pomade','УФ-фільтри','3');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-303-modelling-wax','depot','depot-300-hair-stylings','No. 303 Modelling Wax','Моделювальний віск','Водорозчинний моделювальний віск для сильної, але гнучкої фіксації. Дає змогу змінювати укладку протягом дня після повторної активації водою.','Гнучка фіксація з можливістю рестайлінгу','/images/depot/depot-303-modelling-wax.webp','Нанести потрібну кількість засобу на підсушене рушником або сухе волосся та виконати бажану укладку. Для рестайлінгу змочити руки водою й опрацювати волосся, щоб активувати віск.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-303-modelling-wax';
DELETE FROM product_benefits WHERE product_id='depot-303-modelling-wax';
DELETE FROM product_ingredients WHERE product_id='depot-303-modelling-wax';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-303-modelling-wax','Усі типи волосся');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-303-modelling-wax','Забезпечує сильну й гнучку фіксацію','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-303-modelling-wax','Не залишає відчуття забрудненого волосся','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-303-modelling-wax','Дає змогу змінювати укладку протягом дня','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-303-modelling-wax','Полегшує моделювання','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-303-modelling-wax','Кокосова олія','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-303-modelling-wax','Ботанічний комплекс із 12 рослинних екстрактів','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-303-modelling-wax','Екстракт листя чорного чаю','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-303-modelling-wax','Соняшникова олія','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-303-modelling-wax','Гліцерин','4');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-304-hold-strong-gel','depot','depot-300-hair-stylings','No. 304 Hold Strong Gel','Гель для стайлінгу','Гель сильної фіксації, який надає блиску й допомагає підтримувати укладку протягом дня. Для ефекту мокрого волосся забезпечує максимальний блиск.','Сильна фіксація блискучої укладки','/images/depot/depot-304-hold-strong-gel.webp','Нанести потрібну кількість засобу на підсушене рушником або сухе волосся та виконати бажану укладку. Для рестайлінгу змочити руки водою й опрацювати волосся, щоб активувати гель.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-304-hold-strong-gel';
DELETE FROM product_benefits WHERE product_id='depot-304-hold-strong-gel';
DELETE FROM product_ingredients WHERE product_id='depot-304-hold-strong-gel';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-304-hold-strong-gel','Усі типи волосся');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-304-hold-strong-gel','Забезпечує сильну фіксацію','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-304-hold-strong-gel','Надає блиску','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-304-hold-strong-gel','Підтримує укладку протягом дня','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-304-hold-strong-gel','Дає змогу виконати рестайлінг','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-304-hold-strong-gel','Ботанічний комплекс із 12 рослинних екстрактів','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-304-hold-strong-gel','Полімерні фіксатори','1');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-305-volumizer','depot','depot-300-hair-stylings','No. 305 Volumizer','Текстурувальний спрей','Легкий текстурувальний спрей для додаткового об’єму та контролю волосся. Забезпечує м’яку фіксацію, а повторне нанесення підсилює її.','Надання об’єму, текстури та м’якої фіксації','/images/depot/depot-305-volumizer.webp','Нанести на сухе волосся для фіксації створеної форми. Повторне нанесення підсилює фіксацію.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-305-volumizer';
DELETE FROM product_benefits WHERE product_id='depot-305-volumizer';
DELETE FROM product_ingredients WHERE product_id='depot-305-volumizer';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-305-volumizer','Усі типи волосся');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-305-volumizer','Надає об’єму','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-305-volumizer','Створює текстуру','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-305-volumizer','Забезпечує м’яку фіксацію','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-305-volumizer','Допомагає контролювати укладку','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-305-volumizer','Полімерні фіксатори','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-305-volumizer','Морська сіль','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-305-volumizer','Ботанічний комплекс із 10 рослинних екстрактів','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-305-volumizer','Гліцерин','3');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('depot-306-strong-hairspray','depot','depot-300-hair-stylings','No. 306 Strong Hairspray','Лак для волосся','Лак сильної фіксації для об’єму та контролю готової укладки. Допомагає підтримувати її форму протягом дня, а повторне нанесення підсилює фіксацію.','Сильна фіксація та підтримання об’єму укладки','/images/depot/depot-306-strong-hairspray.webp','Нанести на сухе волосся для фіксації створеної форми. Повторне нанесення підсилює фіксацію.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='depot-306-strong-hairspray';
DELETE FROM product_benefits WHERE product_id='depot-306-strong-hairspray';
DELETE FROM product_ingredients WHERE product_id='depot-306-strong-hairspray';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('depot-306-strong-hairspray','Усі типи волосся');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-306-strong-hairspray','Забезпечує сильну фіксацію','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-306-strong-hairspray','Допомагає зберігати форму протягом дня','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-306-strong-hairspray','Підтримує об’єм','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('depot-306-strong-hairspray','Дає контроль над укладкою','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-306-strong-hairspray','Полімерні фіксатори','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('depot-306-strong-hairspray','Провітамін B5','1');
