-- Adds the H.Q.Beauty hair-care catalog extracted from the supplied presentation.
INSERT INTO brands (id,name,description) VALUES ('hq-beauty','H.Q.Beauty','Швейцарський бренд космецевтичних засобів для догляду за шкірою обличчя, тіла та волосся. Лінійки для волосся поєднують натуральні й органічні компоненти з функціональними комплексами.') ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description;
INSERT INTO product_lines (id,brand_id,name,short_description,description,hair_types,purposes,benefits,keywords,image) VALUES ('hq-beauty-daily-care','hq-beauty','Daily Care','Делікатний щоденний догляд для всіх типів волосся','Серія з органічним екстрактом листя та стебел вівса для частого делікатного догляду. Підходить усім типам волосся, зокрема тонкому й делікатному.','["Усі типи волосся","Тонке","Делікатне"]','["Щоденний догляд","Делікатне очищення","Зволоження"]','["Пом’якшує волосся","Зволожує","Підтримує еластичність","Надає блиску"]','["Щоденний догляд","Вівсяний екстракт","Делікатний догляд"]','/images/hq-beauty/hq-beauty-daily-care.webp') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,hair_types=excluded.hair_types,purposes=excluded.purposes,benefits=excluded.benefits,keywords=excluded.keywords,image=excluded.image;
INSERT INTO product_lines (id,brand_id,name,short_description,description,hair_types,purposes,benefits,keywords,image) VALUES ('hq-beauty-nourish-dry-and-brittle-hair','hq-beauty','Nourish Dry and Brittle Hair','Живильний догляд для сухого, ламкого, тьмяного та кучерявого волосся','Серія з органічним екстрактом волошки для зволоження, захисту й живлення сухого, ламкого, тьмяного та кучерявого волосся.','["Сухе","Ламке","Тьмяне","Кучеряве"]','["Живлення","Зволоження","Зміцнення"]','["Допомагає запобігати ламкості","Пом’якшує волосся","Підвищує еластичність","Надає блиску"]','["Живлення","Волошка","Сухе волосся"]','/images/hq-beauty/hq-beauty-nourish-dry-and-brittle-hair.webp') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,hair_types=excluded.hair_types,purposes=excluded.purposes,benefits=excluded.benefits,keywords=excluded.keywords,image=excluded.image;
INSERT INTO product_lines (id,brand_id,name,short_description,description,hair_types,purposes,benefits,keywords,image) VALUES ('hq-beauty-keep-hair-color','hq-beauty','Keep Hair Color','Захист кольору фарбованого волосся та термозахист','Серія з органічним екстрактом листя червоного винограду для збереження яскравості кольору, пом’якшення та захисту волосся.','["Фарбоване","Усі типи волосся"]','["Збереження кольору","Захист від вимивання пігменту","Термозахист"]','["Зберігає яскравість кольору","Надає блиску","Пом’якшує","Захищає під час укладання"]','["Фарбоване волосся","Захист кольору","Термозахист"]','/images/hq-beauty/hq-beauty-keep-hair-color.webp') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,hair_types=excluded.hair_types,purposes=excluded.purposes,benefits=excluded.benefits,keywords=excluded.keywords,image=excluded.image;
INSERT INTO product_lines (id,brand_id,name,short_description,description,hair_types,purposes,benefits,keywords,image) VALUES ('hq-beauty-restore-damaged-hair','hq-beauty','Restore Damaged Hair','Відновлювальний догляд для пошкодженого волосся','Серія з органічним гідролізованим екстрактом каштана для відновлення структури, зміцнення, живлення та зволоження пошкодженого волосся.','["Пошкоджене","Ламке"]','["Відновлення структури","Зміцнення","Захист від подальших пошкоджень"]','["Підвищує еластичність","Розгладжує","Зволожує","Повертає блиск"]','["Відновлення","Каштан","Пошкоджене волосся"]','/images/hq-beauty/hq-beauty-restore-damaged-hair.webp') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,hair_types=excluded.hair_types,purposes=excluded.purposes,benefits=excluded.benefits,keywords=excluded.keywords,image=excluded.image;
INSERT INTO product_lines (id,brand_id,name,short_description,description,hair_types,purposes,benefits,keywords,image) VALUES ('hq-beauty-hair-loss-control','hq-beauty','Hair Loss Control','Догляд для слабкого волосся та волосся, схильного до випадіння','Серія з органічним екстрактом розмарину для догляду за шкірою голови, зміцнення волосся та підтримки волосяних фолікулів.','["Слабке","Схильне до випадіння","Усі типи волосся"]','["Контроль випадіння","Зміцнення волосся","Догляд за шкірою голови"]','["Сприяє зміцненню волосся","Стимулює кровообіг шкіри голови","Підтримує волосяні фолікули"]','["Випадіння","Розмарин","Зміцнення"]','/images/hq-beauty/hq-beauty-hair-loss-control.webp') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,name=excluded.name,short_description=excluded.short_description,description=excluded.description,hair_types=excluded.hair_types,purposes=excluded.purposes,benefits=excluded.benefits,keywords=excluded.keywords,image=excluded.image;
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-daily-care-shampoo','hq-beauty','hq-beauty-daily-care','Daily Care Shampoo','Шампунь','Шампунь для дбайливого очищення волосся та навіть чутливої шкіри голови. Формула підтримує природний гідроліпідний баланс і надає тонізувальний та освіжальний ефект.','Делікатне щоденне очищення волосся та шкіри голови','/images/hq-beauty/hq-beauty-daily-care-shampoo.webp','Нанести на вологе волосся та шкіру голови, спінити масажними рухами й рівномірно розподілити по довжині. Ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-daily-care-shampoo';
DELETE FROM product_benefits WHERE product_id='hq-beauty-daily-care-shampoo';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-daily-care-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-shampoo','Усі типи волосся');
INSERT INTO hair_types (id,name) VALUES ('Тонке','Тонке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-shampoo','Тонке');
INSERT INTO hair_types (id,name) VALUES ('Делікатне','Делікатне') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-shampoo','Делікатне');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-shampoo','Делікатно очищає','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-shampoo','Підтримує гідроліпідний баланс','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-shampoo','Тонізує та освіжає','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-shampoo','Підвищує еластичність і міцність','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-shampoo','Органічний екстракт кореня імбиру','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-shampoo','Екстракт глоду','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-shampoo','Органічний екстракт листя та стебел вівса','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-daily-care-conditioner','hq-beauty','hq-beauty-daily-care','Daily Care Conditioner','Кондиціонер','Кондиціонер для щоденного зволоження, м’якості та блиску без обтяження. Полегшує розчісування й сприяє відновленню еластичності волосся.','Щоденне зволоження та пом’якшення волосся','/images/hq-beauty/hq-beauty-daily-care-conditioner.webp','Нанести на чисте вологе волосся й рівномірно розподілити по довжині. Залишити на 3–5 хвилин, потім ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-daily-care-conditioner';
DELETE FROM product_benefits WHERE product_id='hq-beauty-daily-care-conditioner';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-daily-care-conditioner';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-conditioner','Усі типи волосся');
INSERT INTO hair_types (id,name) VALUES ('Тонке','Тонке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-conditioner','Тонке');
INSERT INTO hair_types (id,name) VALUES ('Делікатне','Делікатне') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-conditioner','Делікатне');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-conditioner','Полегшує розчісування','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-conditioner','Надає м’якості та блиску','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-conditioner','Покращує еластичність','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-conditioner','Не обтяжує волосся','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-conditioner','Олія асаї','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-conditioner','Олія насіння маракуї','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-conditioner','Органічний екстракт вівса','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-daily-care-mask','hq-beauty','hq-beauty-daily-care','Daily Care Mask','Маска','Маска для інтенсивного зволоження волосся без обтяження. Комбінація рослинних олій та екстракту вівса надає волоссю еластичність і блиск.','Інтенсивне зволоження без обтяження','/images/hq-beauty/hq-beauty-daily-care-mask.webp','Нанести на чисте вологе волосся та рівномірно розподілити по довжині. Залишити на 5–10 хвилин, ретельно змити; використовувати 1–2 рази на тиждень.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-daily-care-mask';
DELETE FROM product_benefits WHERE product_id='hq-beauty-daily-care-mask';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-daily-care-mask';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-mask','Усі типи волосся');
INSERT INTO hair_types (id,name) VALUES ('Тонке','Тонке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-mask','Тонке');
INSERT INTO hair_types (id,name) VALUES ('Делікатне','Делікатне') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-daily-care-mask','Делікатне');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-mask','Інтенсивно зволожує','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-mask','Не обтяжує','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-mask','Підвищує еластичність','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-daily-care-mask','Надає блиску','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-mask','Кокосова олія','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-mask','Органічна олія насіння чіа','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-mask','Органічне масло ши','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-daily-care-mask','Органічний екстракт вівса','3');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-nourish-shampoo','hq-beauty','hq-beauty-nourish-dry-and-brittle-hair','Nourish Dry and Brittle Hair Shampoo','Шампунь','Шампунь для делікатного очищення та живлення сухого, ламкого, тьмяного й кучерявого волосся. Допомагає підвищити еластичність і пружність від коренів до кінчиків.','Делікатне очищення та живлення сухого й ламкого волосся','/images/hq-beauty/hq-beauty-nourish-shampoo.webp','Нанести на вологе волосся та шкіру голови, спінити масажними рухами й рівномірно розподілити по довжині. Ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-nourish-shampoo';
DELETE FROM product_benefits WHERE product_id='hq-beauty-nourish-shampoo';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-nourish-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Сухе','Сухе') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shampoo','Сухе');
INSERT INTO hair_types (id,name) VALUES ('Ламке','Ламке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shampoo','Ламке');
INSERT INTO hair_types (id,name) VALUES ('Тьмяне','Тьмяне') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shampoo','Тьмяне');
INSERT INTO hair_types (id,name) VALUES ('Кучеряве','Кучеряве') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shampoo','Кучеряве');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-shampoo','Делікатно очищає','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-shampoo','Живить','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-shampoo','Підвищує еластичність','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-shampoo','Допомагає зміцнити волосся','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-shampoo','Органічний екстракт календули','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-shampoo','Органічний екстракт оливи','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-shampoo','Органічний екстракт волошки','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-nourish-conditioner','hq-beauty','hq-beauty-nourish-dry-and-brittle-hair','Nourish Dry and Brittle Hair Conditioner','Кондиціонер','Кондиціонер для живлення та зволоження сухого, ламкого, тьмяного й кучерявого волосся. Зміцнює, вирівнює волосся та полегшує розчісування.','Живлення та зволоження сухого й ламкого волосся','/images/hq-beauty/hq-beauty-nourish-conditioner.webp','Нанести на чисте вологе волосся й рівномірно розподілити по довжині. Залишити на 3–5 хвилин, потім ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-nourish-conditioner';
DELETE FROM product_benefits WHERE product_id='hq-beauty-nourish-conditioner';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-nourish-conditioner';
INSERT INTO hair_types (id,name) VALUES ('Сухе','Сухе') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-conditioner','Сухе');
INSERT INTO hair_types (id,name) VALUES ('Ламке','Ламке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-conditioner','Ламке');
INSERT INTO hair_types (id,name) VALUES ('Тьмяне','Тьмяне') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-conditioner','Тьмяне');
INSERT INTO hair_types (id,name) VALUES ('Кучеряве','Кучеряве') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-conditioner','Кучеряве');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-conditioner','Живить і зволожує','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-conditioner','Зміцнює','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-conditioner','Полегшує розчісування','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-conditioner','Надає природного блиску','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-conditioner','Підвищує еластичність','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-conditioner','Органічна олія амаранту','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-conditioner','Олія лісового горіха','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-conditioner','Органічний екстракт волошки','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-nourish-mask','hq-beauty','hq-beauty-nourish-dry-and-brittle-hair','Nourish Dry and Brittle Hair Mask','Маска','Маска для інтенсивного живлення сухого, ламкого й кучерявого волосся без обтяження. Сприяє глибокому відновленню, зволожує та надає м’якості й блиску.','Інтенсивне живлення сухого й ламкого волосся без обтяження','/images/hq-beauty/hq-beauty-nourish-mask.webp','Нанести на чисте вологе волосся та рівномірно розподілити по довжині. Залишити на 5–10 хвилин, ретельно змити; використовувати 1–2 рази на тиждень.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-nourish-mask';
DELETE FROM product_benefits WHERE product_id='hq-beauty-nourish-mask';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-nourish-mask';
INSERT INTO hair_types (id,name) VALUES ('Сухе','Сухе') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-mask','Сухе');
INSERT INTO hair_types (id,name) VALUES ('Ламке','Ламке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-mask','Ламке');
INSERT INTO hair_types (id,name) VALUES ('Тьмяне','Тьмяне') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-mask','Тьмяне');
INSERT INTO hair_types (id,name) VALUES ('Кучеряве','Кучеряве') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-mask','Кучеряве');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-mask','Інтенсивно живить','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-mask','Глибоко зволожує','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-mask','Пом’якшує','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-mask','Надає блиску','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-mask','Не обтяжує','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-mask','Органічне масло ши','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-mask','Органічна мигдальна олія','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-mask','Органічний екстракт волошки','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-nourish-shine-solution','hq-beauty','hq-beauty-nourish-dry-and-brittle-hair','Nourish Dry and Brittle Hair Shine Solution','Флюїд','Незмивний флюїд для відновлення блиску пошкодженого, фарбованого, сухого й ламкого волосся з посіченими кінчиками. Допомагає запобігати зневодненню та надає шовковистості.','Надання блиску та шовковистості сухому й пошкодженому волоссю','/images/hq-beauty/hq-beauty-nourish-shine-solution.webp','Нанести на сухе або вологе волосся. Не змивати.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-nourish-shine-solution';
DELETE FROM product_benefits WHERE product_id='hq-beauty-nourish-shine-solution';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-nourish-shine-solution';
INSERT INTO hair_types (id,name) VALUES ('Пошкоджене','Пошкоджене') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shine-solution','Пошкоджене');
INSERT INTO hair_types (id,name) VALUES ('Фарбоване','Фарбоване') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shine-solution','Фарбоване');
INSERT INTO hair_types (id,name) VALUES ('Сухе','Сухе') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shine-solution','Сухе');
INSERT INTO hair_types (id,name) VALUES ('Ламке','Ламке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shine-solution','Ламке');
INSERT INTO hair_types (id,name) VALUES ('З посіченими кінчиками','З посіченими кінчиками') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-nourish-shine-solution','З посіченими кінчиками');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-shine-solution','Надає блиску','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-shine-solution','Підвищує еластичність','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-shine-solution','Допомагає запобігати зневодненню','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-nourish-shine-solution','Надає шовковистості','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-shine-solution','Олія бабасу','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-shine-solution','Соняшникова олія','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-shine-solution','Екстракт шипшини','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-nourish-shine-solution','Екстракт дамаської троянди','3');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-keep-hair-color-shampoo','hq-beauty','hq-beauty-keep-hair-color','Keep Hair Color Shampoo','Шампунь','Шампунь для дбайливого очищення фарбованого волосся та захисту кольору від вимивання. Допомагає зберігати яскравість і блиск.','Очищення фарбованого волосся зі збереженням кольору','/images/hq-beauty/hq-beauty-keep-hair-color-shampoo.webp','Нанести на вологе волосся та шкіру голови, спінити масажними рухами й рівномірно розподілити по довжині. Ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-keep-hair-color-shampoo';
DELETE FROM product_benefits WHERE product_id='hq-beauty-keep-hair-color-shampoo';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-keep-hair-color-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Фарбоване','Фарбоване') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-keep-hair-color-shampoo','Фарбоване');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-shampoo','Дбайливо очищає','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-shampoo','Захищає колір від вимивання','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-shampoo','Зберігає яскравість','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-shampoo','Підтримує блиск','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-shampoo','Органічний екстракт малини','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-shampoo','Органічний екстракт ягід годжі','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-shampoo','Органічний екстракт листя червоного винограду','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-keep-hair-color-conditioner','hq-beauty','hq-beauty-keep-hair-color','Keep Hair Color Conditioner','Кондиціонер','Кондиціонер для захисту кольору фарбованого волосся. Зволожує, вирівнює кутикулу, надає м’якості й блиску та полегшує розчісування без обтяження.','Захист кольору та кондиціонування фарбованого волосся','/images/hq-beauty/hq-beauty-keep-hair-color-conditioner.webp','Нанести на чисте вологе волосся й рівномірно розподілити по довжині. Залишити на 3–5 хвилин, потім ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-keep-hair-color-conditioner';
DELETE FROM product_benefits WHERE product_id='hq-beauty-keep-hair-color-conditioner';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-keep-hair-color-conditioner';
INSERT INTO hair_types (id,name) VALUES ('Фарбоване','Фарбоване') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-keep-hair-color-conditioner','Фарбоване');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-conditioner','Запобігає передчасному вимиванню кольору','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-conditioner','Зволожує','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-conditioner','Полегшує розчісування','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-conditioner','Надає блиску','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-conditioner','Не обтяжує','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-conditioner','Органічна арганова олія','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-conditioner','Олія авокадо','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-conditioner','Органічний екстракт листя червоного винограду','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-keep-hair-color-mask','hq-beauty','hq-beauty-keep-hair-color','Keep Hair Color Mask','Маска','Маска для фарбованого та схильного до ламкості волосся. Живить і допомагає захищати від тьмяності та вимивання пігменту.','Захист і збереження кольору фарбованого волосся','/images/hq-beauty/hq-beauty-keep-hair-color-mask.webp','Нанести на чисте вологе волосся та рівномірно розподілити по довжині. Залишити на 5–10 хвилин, ретельно змити; використовувати 1–2 рази на тиждень.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-keep-hair-color-mask';
DELETE FROM product_benefits WHERE product_id='hq-beauty-keep-hair-color-mask';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-keep-hair-color-mask';
INSERT INTO hair_types (id,name) VALUES ('Фарбоване','Фарбоване') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-keep-hair-color-mask','Фарбоване');
INSERT INTO hair_types (id,name) VALUES ('Ламке','Ламке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-keep-hair-color-mask','Ламке');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-mask','Зберігає яскравість кольору','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-mask','Допомагає захищати від тьмяності','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-mask','Живить','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-mask','Підтримує сяйво кольору','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-mask','Органічна соняшникова олія','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-mask','Органічна арганова олія','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-mask','Масло ши','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-mask','Гідрогенізовані рослинні олії','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-mask','Органічний екстракт листя червоного винограду','4');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-keep-hair-color-thermal-protector','hq-beauty','hq-beauty-keep-hair-color','Keep Hair Color Thermal Protector','Термозахисний спрей','Незмивний спрей середньої фіксації для захисту волосся під час використання фена, вирівнювача, щипців або термощітки. Надає м’якості, блиску й подовжує ефект укладки.','Термозахист волосся під час гарячого укладання','/images/hq-beauty/hq-beauty-keep-hair-color-thermal-protector.webp','Рівномірно нанести на сухе або вологе волосся по всій довжині перед моделюванням зачіски. Не змивати.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-keep-hair-color-thermal-protector';
DELETE FROM product_benefits WHERE product_id='hq-beauty-keep-hair-color-thermal-protector';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-keep-hair-color-thermal-protector';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Усі типи волосся');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Захищає від високих температур','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Надає шовковистої м’якості','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Посилює блиск','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Подовжує ефект укладки','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Забезпечує середню фіксацію','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Органічний екстракт фініка','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Органічний екстракт пасифлори','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Екстракт неролі','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-keep-hair-color-thermal-protector','Органічний екстракт апельсина','3');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-restore-damaged-hair-shampoo','hq-beauty','hq-beauty-restore-damaged-hair','Restore Damaged Hair Shampoo','Шампунь','Шампунь для делікатного очищення волосся з пошкодженою структурою. М’яко очищає, зволожує та розгладжує, допомагаючи відновити еластичність і блиск.','Делікатне очищення та відновлювальний догляд за пошкодженим волоссям','/images/hq-beauty/hq-beauty-restore-damaged-hair-shampoo.webp','Нанести на вологе волосся та шкіру голови, спінити масажними рухами й рівномірно розподілити по довжині. Ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-restore-damaged-hair-shampoo';
DELETE FROM product_benefits WHERE product_id='hq-beauty-restore-damaged-hair-shampoo';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-restore-damaged-hair-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Пошкоджене','Пошкоджене') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-restore-damaged-hair-shampoo','Пошкоджене');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-shampoo','М’яко очищає','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-shampoo','Зволожує','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-shampoo','Розгладжує','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-shampoo','Відновлює еластичність','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-shampoo','Повертає блиск','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-shampoo','Органічний гідролізований екстракт каштана','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-shampoo','Органічний екстракт насіння пшениці','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-shampoo','Органічний екстракт рису','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-restore-damaged-hair-conditioner','hq-beauty','hq-beauty-restore-damaged-hair','Restore Damaged Hair Conditioner','Кондиціонер','Кондиціонер для відновлення пошкодженої структури волосся. Зволожує, живить і зміцнює, допомагаючи захистити кутикулу від хімічного та кліматичного впливу.','Відновлення та зміцнення пошкодженого волосся','/images/hq-beauty/hq-beauty-restore-damaged-hair-conditioner.webp','Нанести на чисте вологе волосся й рівномірно розподілити по довжині. Залишити на 3–5 хвилин, потім ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-restore-damaged-hair-conditioner';
DELETE FROM product_benefits WHERE product_id='hq-beauty-restore-damaged-hair-conditioner';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-restore-damaged-hair-conditioner';
INSERT INTO hair_types (id,name) VALUES ('Пошкоджене','Пошкоджене') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Пошкоджене');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Зволожує й живить','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Зміцнює структуру','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Допомагає захищати кутикулу','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Підвищує еластичність','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Повертає блиск','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Органічна кунжутна олія','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Органічний екстракт листя та стебел сази курильської','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-conditioner','Органічний гідролізований екстракт каштана','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-restore-damaged-hair-mask','hq-beauty','hq-beauty-restore-damaged-hair','Restore Damaged Hair Mask','Маска','Маска для відновлення пошкодженого та ламкого волосся. Допомагає зміцнювати внутрішню структуру, підвищує гладкість і еластичність волосяного стовбура.','Інтенсивне відновлення пошкодженого й ламкого волосся','/images/hq-beauty/hq-beauty-restore-damaged-hair-mask.webp','Нанести на чисте вологе волосся та рівномірно розподілити по довжині. Залишити на 5–10 хвилин, ретельно змити; використовувати 1–2 рази на тиждень.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-restore-damaged-hair-mask';
DELETE FROM product_benefits WHERE product_id='hq-beauty-restore-damaged-hair-mask';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-restore-damaged-hair-mask';
INSERT INTO hair_types (id,name) VALUES ('Пошкоджене','Пошкоджене') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-restore-damaged-hair-mask','Пошкоджене');
INSERT INTO hair_types (id,name) VALUES ('Ламке','Ламке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-restore-damaged-hair-mask','Ламке');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-mask','Зміцнює структуру','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-mask','Підвищує гладкість','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-mask','Покращує еластичність','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-restore-damaged-hair-mask','Допомагає відновлювати кератинові ланцюги','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-mask','Олія насіння Balanites roxburghii','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-mask','Олія насіння мускусної шипшини','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-restore-damaged-hair-mask','Органічний гідролізований екстракт каштана','2');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-hair-loss-control-shampoo','hq-beauty','hq-beauty-hair-loss-control','Hair Loss Control Shampoo','Шампунь','Шампунь для очищення та зміцнення слабкого волосся або волосся, схильного до випадіння. Тонізує шкіру голови, стимулює кровообіг і підтримує волосяні фолікули.','Очищення та зміцнення волосся, схильного до випадіння','/images/hq-beauty/hq-beauty-hair-loss-control-shampoo.webp','Нанести на вологе волосся та шкіру голови, спінити масажними рухами й рівномірно розподілити по довжині. Ретельно змити водою.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-hair-loss-control-shampoo';
DELETE FROM product_benefits WHERE product_id='hq-beauty-hair-loss-control-shampoo';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-hair-loss-control-shampoo';
INSERT INTO hair_types (id,name) VALUES ('Слабке','Слабке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-hair-loss-control-shampoo','Слабке');
INSERT INTO hair_types (id,name) VALUES ('Схильне до випадіння','Схильне до випадіння') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-hair-loss-control-shampoo','Схильне до випадіння');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Ніжно очищає','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Сприяє зміцненню волосся','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Тонізує шкіру голови','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Стимулює кровообіг','3');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Освіжає','4');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Органічний екстракт розмарину','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Органічний екстракт кропиви дводомної','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Екстракт полину звичайного','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-shampoo','Ментол','3');
INSERT INTO products (id,brand_id,line_id,name,category,description,purpose,image,usage) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','hq-beauty','hq-beauty-hair-loss-control','Hair Loss Control Strengthening Complex','Зміцнювальний комплекс','Незмивний комплекс для шкіри голови та волосся, схильного до випадіння. Допомагає зміцнювати волосяні фолікули й підтримувати фізіологічний ріст волосся.','Зміцнення волосся та догляд за шкірою голови при схильності до випадіння','/images/hq-beauty/hq-beauty-hair-loss-control-strengthening-complex.webp','Нанести на суху чисту шкіру голови по проділах і розподілити м’якими круговими масажними рухами 15–20 секунд, приділяючи увагу кореням і зонам випадіння. Не змивати; застосовувати після миття, але не менше 1–2 разів на тиждень протягом 2 місяців.') ON CONFLICT(id) DO UPDATE SET brand_id=excluded.brand_id,line_id=excluded.line_id,name=excluded.name,category=excluded.category,description=excluded.description,purpose=excluded.purpose,image=excluded.image,usage=excluded.usage;
DELETE FROM product_hair_types WHERE product_id='hq-beauty-hair-loss-control-strengthening-complex';
DELETE FROM product_benefits WHERE product_id='hq-beauty-hair-loss-control-strengthening-complex';
DELETE FROM product_ingredients WHERE product_id='hq-beauty-hair-loss-control-strengthening-complex';
INSERT INTO hair_types (id,name) VALUES ('Усі типи волосся','Усі типи волосся') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Усі типи волосся');
INSERT INTO hair_types (id,name) VALUES ('Слабке','Слабке') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Слабке');
INSERT INTO hair_types (id,name) VALUES ('Схильне до випадіння','Схильне до випадіння') ON CONFLICT DO NOTHING;
INSERT INTO product_hair_types (product_id,hair_type_id) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Схильне до випадіння');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Допомагає зменшувати випадіння','0');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Стимулює кровообіг шкіри голови','1');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Підтримує волосяні фолікули','2');
INSERT INTO product_benefits (product_id,benefit,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Сприяє фізіологічному росту волосся','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Органічний екстракт розмарину','0');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Ментол','1');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Екстракт зеленої кави','2');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Органічний екстракт кропиви','3');
INSERT INTO product_ingredients (product_id,ingredient,position) VALUES ('hq-beauty-hair-loss-control-strengthening-complex','Мікроелементи міді, заліза, магнію та цинку','4');
